kind: pipeline
name: demo-dev

# remove this section if your CPU is amd64 architecture
platform:
  os: linux
  arch: arm64

concurrency:
  limit: 1

volumes:
- name: dot-kube
  temp: {}

steps:

- name: kube config
  image: alpine:3
  environment:
    KUBE_CONFIG:
      from_secret: kube_config
  commands:
  - echo $KUBE_CONFIG | base64 -d > ~/.kube/config
  volumes:
  - name: dot-kube
    path: /root/.kube

- name: terraform init
  image: hashicorp/terraform:1.1.8
  commands:
  - terraform init -backend-config="secret_suffix=dev" -backend-config="namespace=demo-dev"
  volumes:
  - name: dot-kube
    path: /root/.kube

- name: terraform plan
  image: hashicorp/terraform:1.1.8
  commands:
  - terraform plan -var-file="dev.tfvars"
  volumes:
  - name: dot-kube
    path: /root/.kube
  when:
    event:
    - pull_request

- name: terraform apply
  image: hashicorp/terraform:1.1.8
  commands:
  - terraform apply -auto-approve -var-file="dev.tfvars"
  volumes:
  - name: dot-kube
    path: /root/.kube
  when:
    branch:
    - main

trigger:
  branch:
  - main

---
kind: pipeline
name: demo-prod

# remove this section if your CPU is amd64 architecture
platform:
  os: linux
  arch: arm64

concurrency:
  limit: 1

volumes:
- name: dot-kube
  temp: {}

steps:

- name: kube config
  image: alpine:3
  environment:
    KUBE_CONFIG:
      from_secret: kube_config
  commands:
  - echo $KUBE_CONFIG | base64 -d > ~/.kube/config
  volumes:
  - name: dot-kube
    path: /root/.kube

- name: terraform init (dev)
  image: hashicorp/terraform:1.1.8
  commands:
  - terraform init -backend-config="secret_suffix=prod" -backend-config="namespace=demo-prod"
  volumes:
  - name: dot-kube
    path: /root/.kube

- name: terraform apply
  image: hashicorp/terraform:1.1.8
  commands:
  - terraform apply -auto-approve -var-file="prod.tfvars"
  volumes:
  - name: dot-kube
    path: /root/.kube
  when:
    event:
    - promote
    target:
    - prod

trigger:
  event:
  - promote
  target:
  - prod
